# config.py
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1385982868769083402/L0tcoXRMh-top1zZ1dPWjthYXYCb9GUcDUC2eUplgME8JdHOJr8YtfIrxk1c6utgnzgI"
# DISCORD_WEBHOOK_URL ="https://discord.com/api/webhooks/xxxxx"

COIN_LIST = [
    "0GUSDT",
    "1000000BOBUSDT",
    "1000000MOGUSDT",
    "1000BONKUSDT",
    "1000CATUSDT",
    "1000CHEEMSUSDT",
    "1000FLOKIUSDT",
    "1000LUNCUSDT",
    "1000PEPEUSDT",
    "1000RATSUSDT",
    "1000SATSUSDT",
    "1000SHIBUSDT",
    "1000WHYUSDT",
    "1000XECUSDT",
    "1000XUSDT",
    "1INCHUSDT",
    "1MBABYDOGEUSDT",
    "2ZUSDT",
    "4USDT",
    "A2ZUSDT",
    "AAVEUSDT",
    "ACEUSDT",
    "ACHUSDT",
    "ACTUSDT",
    "ACXUSDT",
    "ADAUSDT",
    "AERGOUSDT",
    "AEROUSDT",
    "AEVOUSDT",
    "AGLDUSDT",
    "AGTUSDT",
    "AI16ZUSDT",
    "AIAUSDT",
    "AINUSDT",
    "AIOTUSDT",
    "AIOUSDT",
    "AIUSDT",
    "AIXBTUSDT",
    "AKEUSDT",
    "AKTUSDT",
    "ALCHUSDT",
    "ALGOUSDT",
    "ALICEUSDT",
    "ALLUSDT",
    "ALPINEUSDT",
    "ALTUSDT",
    "ANIMEUSDT",
    "ANKRUSDT",
    "APEUSDT",
    "API3USDT",
    "APTUSDT",
    "ARBUSDT",
    "ARCUSDT",
    "ARIAUSDT",
    "ARKMUSDT",
    "ARKUSDT",
    "ARPAUSDT",
    "ARUSDT",
    "ASRUSDT",
    "ASTERUSDT",
    "ASTRUSDT",
    "ATAUSDT",
    "ATHUSDT",
    "ATOMUSDT",
    "AUCTIONUSDT",
    "AUSDT",
    "AVAAIUSDT",
    "AVAUSDT",
    "AVAXUSDT",
    "AVNTUSDT",
    "AWEUSDT",
    "AXLUSDT",
    "AXSUSDT",
    "B2USDT",
    "B3USDT",
    "BABYUSDT",
    "BANANAS31USDT",
    "BANANAUSDT",
    "BANDUSDT",
    "BANKUSDT",
    "BANUSDT",
    "BARDUSDT",
    "BASUSDT",
    "BATUSDT",
    "BBUSDT",
    "BCHUSDT",
    "BDXNUSDT",
    "BEAMXUSDT",
    "BELUSDT",
    "BERAUSDT",
    "BICOUSDT",
    "BIDUSDT",
    "BIGTIMEUSDT",
    "BIOUSDT",
    "BLESSUSDT",
    "BLURUSDT",
    "BMTUSDT",
    "BNBUSDT",
    "BNTUSDT",
    "BOMEUSDT",
    "BRETTUSDT",
    "BROCCOLI714USDT",
    "BROCCOLIF3BUSDT",
    "BRUSDT",
    "BSVUSDT",
    "BTCDOMUSDT",
    "BTCUSDT",
    "BTRUSDT",
    "BULLAUSDT",
    "BUSDT",
    "C98USDT",
    "CAKEUSDT",
    "CARVUSDT",
    "CATIUSDT",
    "CELOUSDT",
    "CELRUSDT",
    "CETUSUSDT",
    "CFXUSDT",
    "CGPTUSDT",
    "CHESSUSDT",
    "CHILLGUYUSDT",
    "CHRUSDT",
    "CHZUSDT",
    "CKBUSDT",
    "CLOUSDT",
    "COAIUSDT",
    "COMPUSDT",
    "COOKIEUSDT",
    "COSUSDT",
    "COTIUSDT",
    "COWUSDT",
    "CROSSUSDT",
    "CRVUSDT",
    "CTKUSDT",
    "CTSIUSDT",
    "CUDISUSDT",
    "CUSDT",
    "CVCUSDT",
    "CVXUSDT",
    "CYBERUSDT",
    "DAMUSDT",
    "DASHUSDT",
    "DEEPUSDT",
    "DEGENUSDT",
    "DEGOUSDT",
    "DENTUSDT",
    "DEXEUSDT",
    "DFUSDT",
    "DIAUSDT",
    "DMCUSDT",
    "DODOXUSDT",
    "DOGEUSDT",
    "DOGSUSDT",
    "DOLOUSDT",
    "DOODUSDT",
    "DOTUSDT",
    "DRIFTUSDT",
    "DUSDT",
    "DUSKUSDT",
    "DYDXUSDT",
    "DYMUSDT",
    "EDENUSDT",
    "EDUUSDT",
    "EGLDUSDT",
    "EIGENUSDT",
    "ENAUSDT",
    "ENJUSDT",
    "ENSOUSDT",
    "ENSUSDT",
    "EPICUSDT",
    "EPTUSDT",
    "ERAUSDT",
    "ESPORTSUSDT",
    "ETCUSDT",
    "ETHFIUSDT",
    "ETHUSDT",
    "ETHWUSDT",
    "EULUSDT",
    "EVAAUSDT",
    "FARTCOINUSDT",
    "FETUSDT",
    "FFUSDT",
    "FHEUSDT",
    "FIDAUSDT",
    "FILUSDT",
    "FIOUSDT",
    "FISUSDT",
    "FLMUSDT",
    "FLOCKUSDT",
    "FLOWUSDT",
    "FLUIDUSDT",
    "FLUXUSDT",
    "FORMUSDT",
    "FORTHUSDT",
    "FUNUSDT",
    "FUSDT",
    "FXSUSDT",
    "GALAUSDT",
    "GASUSDT",
    "GHSTUSDT",
    "GIGGLEUSDT",
    "GLMUSDT",
    "GMTUSDT",
    "GMXUSDT",
    "GOATUSDT",
    "GPSUSDT",
    "GRASSUSDT",
    "GRIFFAINUSDT",
    "GRTUSDT",
    "GTCUSDT",
    "GUNUSDT",
    "GUSDT",
    "HAEDALUSDT",
    "HANAUSDT",
    "HBARUSDT",
    "HEIUSDT",
    "HEMIUSDT",
    "HFTUSDT",
    "HIGHUSDT",
    "HIPPOUSDT",
    "HIVEUSDT",
    "HMSTRUSDT",
    "HOLOUSDT",
    "HOMEUSDT",
    "HOOKUSDT",
    "HOTUSDT",
    "HUMAUSDT",
    "HUSDT",
    "HYPERUSDT",
    "HYPEUSDT",
    "ICNTUSDT",
    "ICPUSDT",
    "ICXUSDT",
    "IDOLUSDT",
    "IDUSDT",
    "ILVUSDT",
    "IMXUSDT",
    "INITUSDT",
    "INJUSDT",
    "INUSDT",
    "IOSTUSDT",
    "IOTAUSDT",
    "IOTXUSDT",
    "IOUSDT",
    "IPUSDT",
    "JASMYUSDT",
    "JELLYJELLYUSDT",
    "JOEUSDT",
    "JSTUSDT",
    "JTOUSDT",
    "JUPUSDT",
    "KAIAUSDT",
    "KAITOUSDT",
    "KASUSDT",
    "KAVAUSDT",
    "KDAUSDT",
    "KERNELUSDT",
    "KGENUSDT",
    "KMNOUSDT",
    "KNCUSDT",
    "KOMAUSDT",
    "KSMUSDT",
    "LABUSDT",
    "LAUSDT",
    "LAYERUSDT",
    "LDOUSDT",
    "LIGHTUSDT",
    "LINEAUSDT",
    "LINKUSDT",
    "LISTAUSDT",
    "LPTUSDT",
    "LQTYUSDT",
    "LRCUSDT",
    "LSKUSDT",
    "LTCUSDT",
    "LUMIAUSDT",
    "LUNA2USDT",
    "LYNUSDT",
    "MAGICUSDT",
    "MANAUSDT",
    "MANTAUSDT",
    "MASKUSDT",
    "MAVIAUSDT",
    "MAVUSDT",
    "MBOXUSDT",
    "MELANIAUSDT",
    "MEMEUSDT",
    "MERLUSDT",
    "METISUSDT",
    "METUSDT",
    "MEUSDT",
    "MEWUSDT",
    "MILKUSDT",
    "MINAUSDT",
    "MIRAUSDT",
    "MITOUSDT",
    "MLNUSDT",
    "MOCAUSDT",
    "MONUSDT",
    "MOODENGUSDT",
    "MORPHOUSDT",
    "MOVEUSDT",
    "MOVRUSDT",
    "MTLUSDT",
    "MUBARAKUSDT",
    "MUSDT",
    "MYROUSDT",
    "MYXUSDT",
    "NAORISUSDT",
    "NEARUSDT",
    "NEIROUSDT",
    "NEOUSDT",
    "NEWTUSDT",
    "NFPUSDT",
    "NILUSDT",
    "NKNUSDT",
    "NMRUSDT",
    "NOMUSDT",
    "NOTUSDT",
    "NTRNUSDT",
    "NXPCUSDT",
    "OBOLUSDT",
    "OGNUSDT",
    "OGUSDT",
    "OLUSDT",
    "OMUSDT",
    "ONDOUSDT",
    "ONEUSDT",
    "ONGUSDT",
    "ONTUSDT",
    "OPENUSDT",
    "OPUSDT",
    "ORCAUSDT",
    "ORDERUSDT",
    "ORDIUSDT",
    "OXTUSDT",
    "PARTIUSDT",
    "PAXGUSDT",
    "PENDLEUSDT",
    "PENGUUSDT",
    "PEOPLEUSDT",
    "PERPUSDT",
    "PHAUSDT",
    "PHBUSDT",
    "PIPPINUSDT",
    "PIXELUSDT",
    "PLAYUSDT",
    "PLUMEUSDT",
    "PNUTUSDT",
    "POLUSDT",
    "POLYXUSDT",
    "PONKEUSDT",
    "POPCATUSDT",
    "PORT3USDT",
    "PORTALUSDT",
    "POWRUSDT",
    "PROMPTUSDT",
    "PROMUSDT",
    "PROVEUSDT",
    "PTBUSDT",
    "PUFFERUSDT",
    "PUMPBTCUSDT",
    "PUMPUSDT",
    "PUNDIXUSDT",
    "PYTHUSDT",
    "QNTUSDT",
    "QTUMUSDT",
    "QUICKUSDT",
    "QUSDT",
    "RAREUSDT",
    "RAYSOLUSDT",
    "RDNTUSDT",
    "RECALLUSDT",
    "REDUSDT",
    "REIUSDT",
    "RENDERUSDT",
    "RESOLVUSDT",
    "REZUSDT",
    "RIFUSDT",
    "RIVERUSDT",
    "RLCUSDT",
    "RONINUSDT",
    "ROSEUSDT",
    "RPLUSDT",
    "RSRUSDT",
    "RUNEUSDT",
    "RVNUSDT",
    "RVVUSDT",
    "SAFEUSDT",
    "SAGAUSDT",
    "SAHARAUSDT",
    "SANDUSDT",
    "SANTOSUSDT",
    "SAPIENUSDT",
    "SCRTUSDT",
    "SCRUSDT",
    "SEIUSDT",
    "SFPUSDT",
    "SHELLUSDT",
    "SIGNUSDT",
    "SIRENUSDT",
    "SKATEUSDT",
    "SKLUSDT",
    "SKYAIUSDT",
    "SKYUSDT",
    "SLPUSDT",
    "SNXUSDT",
    "SOLUSDT",
    "SOLVUSDT",
    "SOMIUSDT",
    "SONICUSDT",
    "SOONUSDT",
    "SOPHUSDT",
    "SPELLUSDT",
    "SPKUSDT",
    "SPXUSDT",
    "SQDUSDT",
    "SSVUSDT",
    "STBLUSDT",
    "STEEMUSDT",
    "STGUSDT",
    "STORJUSDT",
    "STOUSDT",
    "STRKUSDT",
    "STXUSDT",
    "SUIUSDT",
    "SUNUSDT",
    "SUPERUSDT",
    "SUSDT",
    "SUSHIUSDT",
    "SWARMSUSDT",
    "SWELLUSDT",
    "SXPUSDT",
    "SXTUSDT",
    "SYNUSDT",
    "SYRUPUSDT",
    "SYSUSDT",
    "TACUSDT",
    "TAGUSDT",
    "TAIKOUSDT",
    "TAKEUSDT",
    "TANSSIUSDT",
    "TAOUSDT",
    "TAUSDT",
    "THETAUSDT",
    "THEUSDT",
    "TIAUSDT",
    "TLMUSDT",
    "TNSRUSDT",
    "TOKENUSDT",
    "TONUSDT",
    "TOSHIUSDT",
    "TOWNSUSDT",
    "TRADOORUSDT",
    "TRBUSDT",
    "TREEUSDT",
    "TRUMPUSDT",
    "TRUTHUSDT",
    "TRUUSDT",
    "TRXUSDT",
    "TSTUSDT",
    "TURBOUSDT",
    "TUSDT",
    "TUTUSDT",
    "TWTUSDT",
    "UBUSDT",
    "UMAUSDT",
    "UNIUSDT",
    "USDCUSDT",
    "USELESSUSDT",
    "USTCUSDT",
    "USUALUSDT",
    "VANAUSDT",
    "VANRYUSDT",
    "VELODROMEUSDT",
    "VELVETUSDT",
    "VETUSDT",
    "VFYUSDT",
    "VICUSDT",
    "VINEUSDT",
    "VIRTUALUSDT",
    "VOXELUSDT",
    "VTHOUSDT",
    "VVVUSDT",
    "WALUSDT",
    "WAXPUSDT",
    "WCTUSDT",
    "WIFUSDT",
    "WLDUSDT",
    "WLFIUSDT",
    "WOOUSDT",
    "WUSDT",
    "XAIUSDT",
    "XANUSDT",
    "XCNUSDT",
    "XLMUSDT",
    "XMRUSDT",
    "XNYUSDT",
    "XPINUSDT",
    "XPLUSDT",
    "XRPUSDT",
    "XTZUSDT",
    "XVGUSDT",
    "XVSUSDT",
    "YALAUSDT",
    "YBUSDT",
    "YFIUSDT",
    "YGGUSDT",
    "ZBTUSDT",
    "ZECUSDT",
    "ZENUSDT",
    "ZEREBROUSDT",
    "ZETAUSDT",
    "ZILUSDT",
    "ZKCUSDT",
    "ZKJUSDT",
    "ZKUSDT",
    "ZORAUSDT",
    "ZRCUSDT",
    "ZROUSDT",
    "ZRXUSDT",
    "币安人生USDT"
]

# ==============================
# ⏱️ Khung thời gian cần quét
# ==============================
INTERVALS = ["15m", "30m", "1h"]

# ==============================
# ⚙️ Cấu hình luồng và chu kỳ
# ==============================
MAX_THREADS = 4          # Tăng nếu CPU mạnh
SLEEP_TIME = 180         # 3 phút / 1 chu kỳ quét
SENT_SIGNALS_FILE = "sent_signals.json"

# ==============================
# 📡 Cấu hình dữ liệu Binance
# ==============================
BINANCE_FUTURES_URL = "https://fapi.binance.com/fapi/v1/klines"

# ==============================
# 📈 Cấu hình chỉ báo kỹ thuật
# ==============================
EMA_SHORT = 15
EMA_MID = 20
EMA_LONG = 25

BOLLINGER_PERIOD = 20
BOLLINGER_STD_DEV = 2.0

RSI_PERIOD = 14

STOCH_RSI_PERIOD = 14
STOCH_RSI_SMOOTH_K = 3
STOCH_RSI_SMOOTH_D = 3

MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

# ==============================
# 🔍 Bộ lọc xác nhận tín hiệu
# ==============================
USE_RSI_CONFIRM = True
USE_STOCH_RSI_CONFIRM = True
USE_MACD_CONFIRM = True

# Ngưỡng quá mua / quá bán
RSI_OVERBOUGHT = 70
RSI_OVERSOLD = 30
STOCH_RSI_OVERBOUGHT = 80
STOCH_RSI_OVERSOLD = 20

# ==============================
# ⚡ Bộ lọc biến động Volume
# ==============================
VOL_MULT = 1.3   # Hệ số nhân khối lượng so với trung bình
BB_STD = 2.0     # Độ lệch chuẩn của Bollinger Band

# ==============================
# 🧠 Tùy chỉnh hành vi cảnh báo
# ==============================
ENABLE_PINBAR_ENGULF = True  # Sử dụng mô hình nến xác nhận (Pinbar, Engulfing)
SEND_DUPLICATE_SIGNALS = False  # Không gửi lại tín hiệu đã gửi

# ==============================
# 🧾 Log & Debug
# ==============================
ENABLE_DEBUG_LOG = True
LOG_FILE = "bot_activity.log"

# ==============================
# 🎯 Mức ưu tiên tín hiệu
# ==============================
# Để lọc tín hiệu mạnh hơn: ví dụ phải thỏa cả EMA, Bollinger, RSI cùng hướng
SIGNAL_CONFIRM_STRICT = True

# ==============================
# ✅ Tùy chỉnh hệ thống
# ==============================
# Giới hạn dữ liệu nến tải về
MAX_CANDLES = 500
REQUEST_TIMEOUT = 10
RETRY_COUNT = 3