# config.py
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL_HERE"

COIN_LIST = [
    "BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","DOGEUSDT","ADAUSDT","AVAXUSDT",
    "TRXUSDT","LINKUSDT","MATICUSDT","LTCUSDT","DOTUSDT","UNIUSDT","TONUSDT","NEARUSDT",
    "ICPUSDT","FILUSDT","APTUSDT","ARBUSDT","OPUSDT","ETCUSDT","XLMUSDT","IMXUSDT",
    "SUIUSDT","MKRUSDT","AAVEUSDT","INJUSDT","LDOUSDT","SEIUSDT","RUNEUSDT","GRTUSDT",
    "ALGOUSDT","EGLDUSDT","FLOWUSDT","SNXUSDT","CRVUSDT","CAKEUSDT","DYDXUSDT","PEPEUSDT",
    "SHIBUSDT","FETUSDT","RNDRUSDT","HBARUSDT","CHZUSDT","QNTUSDT","MANAUSDT","XTZUSDT",
    "FTMUSDT","ATOMUSDT","EOSUSDT","KAVAUSDT","1INCHUSDT","SANDUSDT","THETAUSDT","GALAUSDT",
    "ENJUSDT","ZILUSDT","BATUSDT","XECUSDT","LRCUSDT","BLURUSDT","WAVESUSDT","HOTUSDT",
    "ANKRUSDT","CELRUSDT","OMGUSDT","RAYUSDT","COMPUSDT","YFIUSDT","C98USDT","ARBUSDT",
    "STXUSDT","KSMUSDT","BALUSDT","BELUSDT","OPUSDT","NEOUSDT","ROSEUSDT","CTKUSDT",
    "BANDUSDT","DASHUSDT","ZECUSDT","CVCUSDT","KLAYUSDT","SRMUSDT","CHRUSDT","MTLUSDT",
    "TRBUSDT","SKLUSDT","STORJUSDT","SXPUSDT","VETUSDT","DENTUSDT","OCEANUSDT","ICXUSDT",
    "RLCUSDT","NKNUSDT","GTCUSDT","CFXUSDT"
]

TIMEFRAMES = ["15m", "30m", "1h"]
EMA_SHORT, EMA_MID, EMA_LONG = 10, 22, 55
BB_STD = 1.6
VOL_MULT = 1.3
